version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  backend:
    build: .
    container_name: backend
    ports:
      - "3001:8080"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mongodb://mongodb:27017/expressRestDB?replicaSet=rs0&directConnection=true
      - FRONTEND_URL=http://chatbot-editor.ddns.net:3000
    depends_on:
      - mongodb
    networks:
      - app-network
    restart: always

  frontend:
    build:
      context: ../chatbot-frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_ENV=production
      - REACT_APP_BACKEND_URL=http://chatbot-editor.ddns.net:3001
    networks:
      - app-network
    restart: always

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "3002:27017"
    volumes:
      - mongo-data:/data/db
      - ./init.js:/docker-entrypoint-initdb.d/init.js:ro
    command: ["mongod", "--replSet", "rs0"]
    networks:
      - app-network
    restart: always

volumes:
  mongo-data: