version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      - backend
      - frontend
    networks:
      - app-network
    restart: always

  backend:
    build: .
    container_name: backend
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mongodb://mongodb:27017/expressRestDB?replicaSet=rs0&directConnection=true
      - FRONTEND_URL=http://chatbot-editor.ddns.net
    networks:
      - app-network
    restart: always

  frontend:
    build:
      context: ../chatbot-frontend
    container_name: frontend
    environment:
      - REACT_APP_ENV=production
      - REACT_APP_BACKEND_URL=http://chatbot-editor.ddns.net/api
    networks:
      - app-network
    restart: always

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "3002:27017"
    volumes:
      - mongo-data:/data/db
      - ./init.js:/docker-entrypoint-initdb.d/init.js:ro
    command: ["mongod", "--replSet", "rs0"]
    networks:
      - app-network
    restart: always

volumes:
  mongo-data: