version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "${CADDY_HTTP_PORT:-80}:80"
      - "${CADDY_HTTPS_PORT:-443}:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend
      - frontend
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - app-network
    restart: always

  backend:
    build: .
    container_name: backend
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - DATABASE_URL=mongodb://mongodb:27017/expressRestDB?replicaSet=rs0&directConnection=true
      - FRONTEND_URL=${FRONTEND_URL:-https://localhost}
    networks:
      - app-network
    restart: always

  frontend:
    build:
      context: ../chatbot-frontend
    container_name: frontend
    environment:
      - REACT_APP_ENV=${NODE_ENV:-development}}
      - REACT_APP_BACKEND_URL=${BACKEND_URL:-https://localhost}
    networks:
      - app-network
    restart: always

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongo-data:/data/db
      - ./init.js:/docker-entrypoint-initdb.d/init.js:ro
    command: [ "mongod", "--replSet", "rs0" ]
    networks:
      - app-network
    restart: always

volumes:
  mongo-data:
  caddy_data:
  caddy_config:
