version: '3.8'

services:
  backend:
    build: .
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mongodb://localhost:27017/expressRestDB?replicaSet=rs0
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - mongodb

  frontend:
    build:
      context: ../chatbot-frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_ENV=production
      - REACT_APP_BACKEND_URL=http://localhost:8080

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./init.js:/docker-entrypoint-initdb.d/init.js:ro
    command: ["mongod", "--replSet", "rs0"]

volumes:
  mongo-data: