version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - default

  frontend:
    build:
      context: ../chatbot-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - default

networks:
  default:
    driver: bridge
